### ISSUE TITLE
Some influence on the generated functions

### ISSUE THREAD

**Issue by s00500** [dvcrn/go-rekordbox#3]
Hi,
I was checking the generated functions.. and thinking on how they are created, eg I am missing the 

DjmdRecommendLikeByContentId2 ...

and DjmdRecommendLikeByContentId1ContentId2 seems oddly useless to me

Is there any way to influence these generations ? or can we write custom queries in the library ? (Of course I can do it in my application but it might be useful in the library...)

Eg: I would likea version of DjmdRecommendLikeByContentId1ContentId2 that uses an OR instead of the (rather pointless) AND

What is the best way to do this ? (Disclaimer: I have not looked into the way you are generating these, just thought I ask first :-) )

**Comment by dvcrn** [comment]
The definitions are generated with https://github.com/xo/xo, which uses the database schema (indices, tables, etc.) together with templates to generate the golang files. The templates are in https://github.com/dvcrn/go-rekordbox/tree/main/tpl

The reason for `DjmdRecommendLikeByContentId1ContentId2` existing is because the rekordbox database has an Index on `DjmdRecommendLike` that includes `ContentId1` and `ContentId2`: https://github.com/dvcrn/go-rekordbox/blob/main/db/schema.sql#L194

You can create your own files to extend this library like I did with `djmdsonghistory` - https://github.com/dvcrn/go-rekordbox/blob/main/rekordbox/djmdsonghistory.go

Or you can also use `client.GetDB()` to get the DB instance directly which you can use to submit raw queries (https://github.com/dvcrn/go-rekordbox#usage-without-generated-helper-functions). In the end, all the helpers are doing are doing is just using the db object and submitting queries that match the indices, eg.

```
db := c.db

	const sqlstr = `SELECT * FROM DjmdSongHistory ORDER BY created_at DESC LIMIT $1`
	rows, err := db.QueryContext(ctx, sqlstr, limit)
	if err != nil {
		return nil, logerror(err)
	}

	defer rows.Close()

	res, err := scanDjmdSongHistoryRows(rows)
	if err != nil {
		return nil, logerror(err)
	}
	return res, nil
```

**Comment by dvcrn** [comment]
I'll close this, let me know if you have any other questions 👍
